Repository COSC481W-2020Fall/cosc481w-581-2020-fall-nutrition-helper, pull requests merged in 2020-09, with the labels that each got.

#4 added project and prototype description to README
  README.md
Labels: documentation

#6 added the language and framework used to the README.md
  README.md
Labels: documentation

#8 Mentioned dynamic nature of food nutrition page
  README.md
Labels: documentation

#10 Updated README.md Description a bit
  README.md
Labels: documentation

#20 added basic db retrieval functionality
  README.md
  nutrihelper/db.sqlite3
  nutrihelper/nutrihelper/__pycache__/__init__.cpython-38.pyc
  nutrihelper/nutrihelper/__pycache__/settings.cpython-37.pyc
  nutrihelper/nutrihelper/__pycache__/settings.cpython-38.pyc
  nutrihelper/nutrihelper/__pycache__/urls.cpython-38.pyc
  nutrihelper/prototype/__pycache__/__init__.cpython-38.pyc
  nutrihelper/prototype/__pycache__/admin.cpython-37.pyc
  nutrihelper/prototype/__pycache__/admin.cpython-38.pyc
  nutrihelper/prototype/__pycache__/apps.cpython-38.pyc
  nutrihelper/prototype/__pycache__/models.cpython-37.pyc
  nutrihelper/prototype/__pycache__/models.cpython-38.pyc
  nutrihelper/prototype/__pycache__/urls.cpython-37.pyc
  nutrihelper/prototype/__pycache__/urls.cpython-38.pyc
  nutrihelper/prototype/__pycache__/views.cpython-37.pyc
  nutrihelper/prototype/__pycache__/views.cpython-38.pyc
  nutrihelper/prototype/admin.py
  nutrihelper/prototype/migrations/0001_initial.py
  nutrihelper/prototype/migrations/__pycache__/0001_initial.cpython-37.pyc
  nutrihelper/prototype/migrations/__pycache__/0001_initial.cpython-38.pyc
  nutrihelper/prototype/migrations/__pycache__/__init__.cpython-38.pyc
  nutrihelper/prototype/models.py
  nutrihelper/prototype/templates/prototype/description.html
  nutrihelper/prototype/templates/prototype/index.html
  nutrihelper/prototype/templates/prototype/nutrifacts.html
  nutrihelper/prototype/urls.py
  nutrihelper/prototype/views.py
  requirements.txt
Labels: enhancement

#45 added comments to views.py, urls.py and admin.py
  nutrihelper/prototype/admin.py
  nutrihelper/prototype/urls.py
  nutrihelper/prototype/views.py
Labels: documentation

#46 removed tracked .pyc files and updated README.md
  README.md
  nutrihelper/nutrihelper/__pycache__/__init__.cpython-37.pyc
  nutrihelper/nutrihelper/__pycache__/__init__.cpython-38.pyc
  nutrihelper/nutrihelper/__pycache__/settings.cpython-37.pyc
  nutrihelper/nutrihelper/__pycache__/settings.cpython-38.pyc
  nutrihelper/nutrihelper/__pycache__/urls.cpython-37.pyc
  nutrihelper/nutrihelper/__pycache__/urls.cpython-38.pyc
  nutrihelper/nutrihelper/__pycache__/wsgi.cpython-37.pyc
  nutrihelper/prototype/__pycache__/__init__.cpython-37.pyc
  nutrihelper/prototype/__pycache__/__init__.cpython-38.pyc
  nutrihelper/prototype/__pycache__/admin.cpython-37.pyc
  nutrihelper/prototype/__pycache__/admin.cpython-38.pyc
  nutrihelper/prototype/__pycache__/apps.cpython-37.pyc
  nutrihelper/prototype/__pycache__/apps.cpython-38.pyc
  nutrihelper/prototype/__pycache__/models.cpython-37.pyc
  nutrihelper/prototype/__pycache__/models.cpython-38.pyc
  nutrihelper/prototype/__pycache__/urls.cpython-37.pyc
  nutrihelper/prototype/__pycache__/urls.cpython-38.pyc
  nutrihelper/prototype/__pycache__/views.cpython-37.pyc
  nutrihelper/prototype/__pycache__/views.cpython-38.pyc
  nutrihelper/prototype/migrations/__pycache__/0001_initial.cpython-37.pyc
  nutrihelper/prototype/migrations/__pycache__/0001_initial.cpython-38.pyc
  nutrihelper/prototype/migrations/__pycache__/__init__.cpython-37.pyc
  nutrihelper/prototype/migrations/__pycache__/__init__.cpython-38.pyc
Labels: documentation

#50 Comments in search-related code, and made the search more user friendly
  nutrihelper/prototype/templates/prototype/search.html
  nutrihelper/prototype/views.py
Labels: appearance, documentation
